# /Users/sebastianuskh/.config/tmuxinator/pf.yml

name: pf
root: ~/

windows:
  - main:
      panes:
        - xdg-open "https://secure.payfazz.com/vpn" && sudo openvpn ~/vpn/client.ovpn
        - aws sso login
        - vault login -method=oidc
