# Base environment configuration
# Single source of truth for all shell environments

# Basic environment variables
environment:
  EDITOR: nvim
  VISUAL: nvim
  PAGER: bat
  BROWSER: chrome
  CHROME_EXECUTABLE: chrome
  DISPLAY: ":0.0"
  LC_CTYPE: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  DOCKER_DEFAULT_PLATFORM: linux/amd64
  PIP_REQUIRE_VIRTUALENV: "true"

# Tool configurations
tools:
  # FZF configuration
  FZF_DEFAULT_OPTS: |
    --layout=reverse
    --info=inline
    --height=70%
    --preview-window=:hidden
    --preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
    --preview-window=right:60%:wrap
    --bind '?:toggle-preview'
  FZF_DEFAULT_COMMAND: "rg --files --hidden"
  FZF_CTRL_T_COMMAND: "$FZF_DEFAULT_COMMAND"

# Project directories
directories:
  CODE: "$HOME/Code"
  GOPATH: "$CODE/go"

# PATH configuration (in priority order - first = highest priority)
path:
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - $HOME/.local/share/nvim/mason/bin
  - $HOME/.local/bin
  - $HOME/.cargo/bin
  - $HOME/dotfiles/bin
  - $GOPATH/bin
  - $HOME/.krew/bin
  - $HOME/.pub-cache/bin
  - /usr/lib/node_modules/.bin
  - /opt/homebrew/opt/mysql-client/bin
  - /opt/homebrew/opt/libpq/bin
  - /Applications/Pritunl.app/Contents/Resources
