# Hardware configuration for Steam Deck
# This file should be generated by nixos-generate-config --hardware-config
{ config, lib, pkgs, modulesPath, ... }:

{
  # Placeholder - replace with actual hardware configuration
  # Run: nixos-generate-config --hardware-config --show-hardware-config
}
