k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kubefazz-mngr
  currentCluster: k8mgmt0
  clusters:
    arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_sandbox:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - argocd
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    cfz_prod:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    cfz_prod-8d88t754gb:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - kube-system
        - cashfazz
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    cop-staging:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - argocd
        - default
      view:
        active: ingress
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    dci_prod:
      namespace:
        active: cop
        lockFavorites: false
        favorites:
        - cop
        - default
      view:
        active: secret
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_vibrant-arcana-324210_asia-southeast2-a_development:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - cert-manager
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_vibrant-arcana-324210_asia-southeast2-a_wallet-service-cluster:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: ing
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    k8cop1:
      namespace:
        active: cop
        lockFavorites: false
        favorites:
        - all
        - cop
        - default
      view:
        active: ingress
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    k8mgmt0:
      namespace:
        active: observability
        lockFavorites: false
        favorites:
        - security
        - observability
        - all
        - argocd
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    kubefazz:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - vswh
        - frontend
        - ingress-nginx
        - billfazz
        - neu
        - post
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    kubefazz-dev:
      namespace:
        active: neu
        lockFavorites: false
        favorites:
        - neu
        - bisainvest
        - all
        - post
        - default
      view:
        active: statefulset
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    ntt_test:
      namespace:
        active: cop
        lockFavorites: false
        favorites:
        - all
        - cop
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    xfers_prod:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - id
        - sg
        - all
        - internal
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    xfers_staging_pomerium:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: ing
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/2q/rfjxyxwn4zxg_nw417s27fw40000gn/T/k9s-screens-sebastianuskh
