k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_prod
  currentCluster: arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_prod
  clusters:
    arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_prod:
      namespace:
        active: all
        favorites:
        - all
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_sandbox:
      namespace:
        active: all
        favorites:
        - argocd
        - all
        - default
      view:
        active: ingress
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:ap-southeast-1:873824401526:cluster/xfers_staging:
      namespace:
        active: all
        favorites:
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_vibrant-arcana-324210_asia-southeast2-a_development:
      namespace:
        active: all
        favorites:
        - cert-manager
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_vibrant-arcana-324210_asia-southeast2-a_wallet-service-cluster:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: ing
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    k8cop1:
      namespace:
        active: cop
        favorites:
        - cop
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    k8mgmt0:
      namespace:
        active: argocd
        favorites:
        - argocd
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/2q/rfjxyxwn4zxg_nw417s27fw40000gn/T/k9s-screens-sebastianuskh
